version: "3.9"

services:
  postgres:
    image: "postgres:13-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: budget-buddy-db-test
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: 123@Mudar
    volumes:
      - /var/lib/postgresql/data
